### PR TITLE
#3 - Resolved  cuts off iframes on Edge.

### PR DESCRIPTION
**Pull request by felansu**
- Tested on Edge 38.14393.0.0, Chrome 56.0.2924.87 (64-bit) and Firefox 51.0.1 (32-bit)

### CODE REVIEW

**Comment by LeaVerou** [comment]
That looks like it would make them longer than needed in every browser, since 100vh is the height of the entire viewport.

**Comment by felansu** [comment]
@LeaVerou I thought that was the goal

**Comment by LeaVerou** [comment]
No, the goal is 100vh minus the height of the URL bar.

**Comment by felansu** [comment]
@LeaVerou now its correct ? 💃

**Comment by LeaVerou** [comment]
`body` already has `min-height: 100vh` so nothing should be needed on `body, html`. If your changes fix the issue, I bet just applying `height: 100%` on `iframe` fixes it just the same. However, the right approach is to figure out why a problem happens before trying to fix it. Edge supports flexbox. So, why does this happen? Is it a bug when iframes are flex items or something else?

**Comment by felansu** [comment]
@LeaVerou just applying `height: 100%` don't work in edge, is for this reason need be setted in `html, body, iframe`

**Pull request closed without merging**
